SELECT * FROM public.dim_time
ORDER BY id ASC 

ALTER TABLE dim_time
ALTER COLUMN "time" TYPE TIMESTAMP WITHOUT TIME ZONE 
USING (CURRENT_DATE + "time"::INTERVAL);

ALTER TABLE dim_time
ALTER COLUMN "time" TYPE TIME WITHOUT TIME ZONE 
USING "time"::TIME;